# Generated by Django 5.2.8 on 2025-11-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Payment Intent ID"
                    ),
                ),
                (
                    "checkout_session_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Checkout Session ID"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Montant")),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Statut")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "webhook_received",
                    models.BooleanField(default=False, verbose_name="Webhook reçu"),
                ),
                ("webhook_data", models.JSONField(blank=True, default=dict)),
                ("webhook_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_payments",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Stripe",
                "verbose_name_plural": "Paiements Stripe",
                "db_table": "stripe_payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
