# Generated by Django 5.2.8 on 2025-11-28 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Titre"
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom/Auteur")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Légende/Sous-titre"
                    ),
                ),
                (
                    "prix",
                    models.PositiveIntegerField(
                        help_text="Prix en centimes (ex: 2500 = 25€)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix",
                    ),
                ),
                (
                    "code_bare",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="Code-barres ISBN",
                    ),
                ),
                (
                    "nombre_pages",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de pages"
                    ),
                ),
                (
                    "largeur_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Largeur (cm)",
                    ),
                ),
                (
                    "hauteur_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Hauteur (cm)",
                    ),
                ),
                (
                    "epaisseur_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Épaisseur (cm)",
                    ),
                ),
                (
                    "poids_grammes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Poids (grammes)"
                    ),
                ),
                (
                    "date_publication",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "editeur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Éditeur"
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        default="Français", max_length=50, verbose_name="Langue"
                    ),
                ),
                (
                    "quantites",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Stock disponible",
                        verbose_name="Quantité en stock",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Titre SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Description SEO"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Vues"),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ventes"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mise en avant"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Livre",
                "verbose_name_plural": "Livres",
                "db_table": "books",
                "ordering": ["-created_at"],
            },
        ),
    ]
