# Generated by Django 5.2.8 on 2025-12-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jti",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="JTI (Token ID)",
                    ),
                ),
                ("token", models.TextField(verbose_name="Token")),
                (
                    "blacklisted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Blacklisté le"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Blacklist",
                "verbose_name_plural": "Tokens Blacklist",
                "db_table": "token_blacklist_custom",
            },
        ),
    ]
