# Generated by Django 5.2.8 on 2025-12-01 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_tokenblacklist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenblacklist",
            options={
                "verbose_name": "Token Invalidation",
                "verbose_name_plural": "Tokens Invalidation",
            },
        ),
        migrations.RemoveField(
            model_name="tokenblacklist",
            name="blacklisted_at",
        ),
        migrations.RemoveField(
            model_name="tokenblacklist",
            name="jti",
        ),
        migrations.RemoveField(
            model_name="tokenblacklist",
            name="token",
        ),
        migrations.AddField(
            model_name="tokenblacklist",
            name="invalidated_before",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Tokens invalides avant"
            ),
        ),
        migrations.AlterField(
            model_name="tokenblacklist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterModelTable(
            name="tokenblacklist",
            table="token_invalidation",
        ),
    ]
