# Generated by Django 5.2.8 on 2025-12-01 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_tokenblacklist_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(verbose_name="Access Token")),
                ("refresh_token", models.TextField(verbose_name="Refresh Token")),
                (
                    "jti",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="JTI (Token ID)"
                    ),
                ),
                (
                    "refresh_jti",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Refresh JTI"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_blacklisted",
                    models.BooleanField(default=False, verbose_name="Blacklisté"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "refresh_expires_at",
                    models.DateTimeField(verbose_name="Refresh expire le"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Administrateur",
                "verbose_name_plural": "Tokens Administrateurs",
                "db_table": "admin_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="TokenBlacklist",
        ),
        migrations.AddIndex(
            model_name="admintoken",
            index=models.Index(
                fields=["admin", "is_active"], name="admin_token_admin_i_8fd66d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admintoken",
            index=models.Index(fields=["jti"], name="admin_token_jti_cfe749_idx"),
        ),
    ]
