# Generated by Django 5.2.8 on 2025-12-01 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_admintoken_delete_tokenblacklist_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminToken",
        ),
    ]
