# Generated by Django 5.2.8 on 2025-12-01 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_delete_admintoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="jwt_token_id",
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100),
        ),
    ]
