# Generated by Django 5.2.8 on 2025-12-01 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_admin_jwt_token_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="jwt_token_id",
        ),
    ]
