# Generated by Django 5.2.8 on 2025-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_tokenblacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="active_refresh_token_jti",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="JTI du token actif"
            ),
        ),
        migrations.DeleteModel(
            name="TokenBlacklist",
        ),
    ]
