# Generated by Django 5.2.8 on 2025-11-28 17:10

import django.db.models.deletion
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=media.models.book_image_upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cover_front", "Couverture (1ère page)"),
                            ("cover_back", "Quatrième de couverture (dernière page)"),
                            ("content", "Aperçu contenu"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Type d'image",
                    ),
                ),
                (
                    "is_main_cover",
                    models.BooleanField(
                        default=False, verbose_name="Image de couverture principale"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Texte alternatif"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="books.book",
                        verbose_name="Livre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de livre",
                "verbose_name_plural": "Images de livres",
                "db_table": "book_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(max_length=500, verbose_name="URL de la vidéo"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Titre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="books.book",
                        verbose_name="Livre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vidéo de livre",
                "verbose_name_plural": "Vidéos de livres",
                "db_table": "book_videos",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
