# Generated by Django 5.2.8 on 2025-12-03 01:30

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookvideo",
            name="video_url",
        ),
        migrations.AddField(
            model_name="bookvideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=media.models.book_video_upload_path,
                verbose_name="Fichier vidéo",
            ),
        ),
    ]
