# Generated by Django 5.2.8 on 2025-11-28 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Code ISO"
                    ),
                ),
                (
                    "shipping_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Frais de port en centimes",
                        verbose_name="Frais de port",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "db_table": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("voie", models.CharField(max_length=255, verbose_name="Rue")),
                ("numero_voie", models.CharField(max_length=20, verbose_name="Numéro")),
                (
                    "complement_adresse",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Complément d'adresse"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(max_length=20, verbose_name="Code postal"),
                ),
                ("ville", models.CharField(max_length=255, verbose_name="Ville")),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Stripe Checkout Session ID",
                    ),
                ),
                ("subtotal", models.PositiveIntegerField(verbose_name="Sous-total")),
                (
                    "shipping_cost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Frais de port"
                    ),
                ),
                ("total", models.PositiveIntegerField(verbose_name="Total")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de livraison"),
                            ("delivered", "Livrée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Numéro de suivi"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Livré le"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_title",
                    models.CharField(max_length=255, verbose_name="Titre du livre"),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(verbose_name="Prix unitaire"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="books.book",
                        verbose_name="Livre",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de commande",
                "verbose_name_plural": "Articles de commandes",
                "db_table": "order_items",
            },
        ),
    ]
