# Generated by Django 5.2.8 on 2025-11-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.PositiveIntegerField(default=0, verbose_name="Sous-total"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(default=0, verbose_name="Total"),
        ),
    ]
