# Generated by Django 5.2.8 on 2025-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_subtotal_alter_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Stripe Checkout Session ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Stripe Payment Intent ID",
            ),
        ),
    ]
